apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::973148520897:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14HO7FY4F83ZQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::973148520897:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-23T20:32:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "880"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a5840a66-55ca-4817-af5a-5cbbd632aa81
